app:
  name: grpcx-example-client
  version: 1.1.0
  env: dev
  debug: no
grpcc:
  addr: localhost:50051
  insecure: true
  block: true
  timeout: 10s
logging:
  level: debug  #0 panic 0 fatal 1 error 2 warn 3 info 4 debug 5 trace 6
  report_caller: yes
  no_colors: false
  caller_first: no